"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DEFAULT_COLLECTION_SETTINGS, type CollectionSettings, type CollectionRule } from "@/lib/collection-rules";
import type { ReportRow } from "@/lib/collection-report-types";

function RuleRows({ rules, onChange }: { rules: CollectionRule[]; onChange: (rules: CollectionRule[])=>void }) {
  return <div className="space-y-3">{rules.map((rule,index) => <div key={index} className="grid items-end gap-2 sm:grid-cols-[90px_1fr_1fr_auto]"><label className="text-xs">Dia relativo<Input type="number" min={-30} max={365} value={rule.days} onChange={e=>onChange(rules.map((r,i)=>i===index ? {...r,days:Number(e.target.value)} : r))} /></label><label className="text-xs">Nome da etapa<Input value={rule.label} onChange={e=>onChange(rules.map((r,i)=>i===index ? {...r,label:e.target.value} : r))} /></label><label className="text-xs">Template<Input list="collection-template-names" value={rule.template} onChange={e=>onChange(rules.map((r,i)=>i===index ? {...r,template:e.target.value} : r))} /></label><Button variant="ghost" onClick={()=>onChange(rules.filter((_,i)=>i!==index))}>Remover</Button></div>)}<Button variant="outline" onClick={()=>onChange([...rules,{ days: 3, label: "Nova etapa", template: "" }])}>Adicionar etapa</Button></div>;
}
export function CollectionRuleEditor({ customers }: { customers: ReportRow[] }) {
  const [config,setConfig]=useState<CollectionSettings|null>(null),[message,setMessage]=useState("");
  const [busy,setBusy]=useState(false),[templates,setTemplates]=useState<string[]>([]);
  const [newName,setNewName]=useState(""),[customerId,setCustomerId]=useState("");
  useEffect(()=>{ fetch("/api/collections/settings").then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setConfig(data.config);}).catch(e=>setMessage(e.message)); },[]);
  const choices=[...new Map(customers.map(row=>[row.snapshot.customer_id,row.snapshot.name])).entries()];
  async function save() {
    setBusy(true);setMessage("");
    try { const r=await fetch("/api/collections/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(config)});const data=await r.json();if(!r.ok)throw new Error(data.error);setMessage("Régua salva. Novos relatórios e novas prévias usarão estas regras."); } catch(e){setMessage(e instanceof Error?e.message:"Não foi possível salvar.");} finally{setBusy(false);}
  }
  if(!config)return <p className="text-sm">{message||"Carregando configuração…"}</p>;
  return <section className="space-y-5 rounded-2xl border bg-card p-5"><h2 className="text-lg font-semibold">Configurar régua</h2><p className="text-sm text-muted-foreground">Use dias relativos ao vencimento: −5 para aviso antecipado, 0 para o vencimento e números positivos para atraso. Fins de semana e feriados passam para o próximo dia útil. Se duas etapas coincidirem, vale a de menor dia relativo.</p>
    <datalist id="collection-template-names">{templates.map(name=><option key={name} value={name}/>)}</datalist><Button variant="outline" onClick={async()=>{try{const r=await fetch("/api/collections/settings?templates=1");const data=await r.json();if(!r.ok)throw new Error(data.error);setTemplates(data.templates.map((t:{name:string})=>t.name));setMessage(`${data.templates.length} templates disponíveis para seleção.`);}catch(e){setMessage(e instanceof Error?e.message:"Falha ao consultar templates.");}}}>Carregar templates do Chat Jurídico</Button>
    <details open><summary className="mb-3 cursor-pointer font-medium">Régua padrão</summary><RuleRows rules={config.rules} onChange={rules=>setConfig({...config,rules})}/></details>
    <div className="border-t pt-4"><h3 className="font-medium">Categorias de clientes</h3><div className="my-3 flex gap-2"><Input placeholder="Nome da categoria" value={newName} onChange={e=>setNewName(e.target.value)}/><Button variant="outline" disabled={!newName.trim()} onClick={()=>{setConfig({...config,categories:[...config.categories,{id:crypto.randomUUID(),name:newName.trim(),rules:structuredClone(config.rules)}]});setNewName("");}}>Criar categoria</Button></div>{config.categories.map(category=><details key={category.id} className="my-3 rounded-lg border p-3"><summary className="cursor-pointer font-medium">{category.name}</summary><div className="mt-3"><RuleRows rules={category.rules} onChange={rules=>setConfig({...config,categories:config.categories.map(c=>c.id===category.id?{...c,rules}:c)})}/></div></details>)}</div>
    <div className="border-t pt-4"><h3 className="font-medium">Exceções por cliente</h3><p className="my-2 text-sm text-muted-foreground">Selecione um cliente de um relatório aberto para atribuir uma categoria ou uma régua exclusiva.</p><div className="flex flex-wrap gap-2"><select className="h-10 min-w-56 flex-1 rounded-md border bg-card px-3" value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Selecione o cliente</option>{choices.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><Button variant="outline" disabled={!customerId || config.customers.some(c=>c.customerId===customerId)} onClick={()=>{setConfig({...config,customers:[...config.customers,{customerId,name:choices.find(([id])=>id===customerId)?.[1]??customerId,categoryId:null,rules:null}]});setCustomerId("");}}>Personalizar cliente</Button></div>
    {config.customers.map(customer=><details key={customer.customerId} className="my-3 rounded-lg border p-3"><summary className="cursor-pointer font-medium">{customer.name}</summary><div className="mt-3 space-y-3"><label className="block text-sm">Categoria<select className="ml-2 h-10 rounded-md border bg-card px-3" value={customer.categoryId??""} onChange={e=>setConfig({...config,customers:config.customers.map(c=>c.customerId===customer.customerId?{...c,categoryId:e.target.value||null}:c)})}><option value="">Padrão</option>{config.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={customer.rules!==null} onChange={e=>setConfig({...config,customers:config.customers.map(c=>c.customerId===customer.customerId?{...c,rules:e.target.checked?structuredClone(config.categories.find(x=>x.id===customer.categoryId)?.rules??config.rules??DEFAULT_COLLECTION_SETTINGS.rules):null}:c)})}/>Usar régua exclusiva para este cliente</label>{customer.rules!==null&&<RuleRows rules={customer.rules} onChange={rules=>setConfig({...config,customers:config.customers.map(c=>c.customerId===customer.customerId?{...c,rules}:c)})}/>}<Button variant="ghost" onClick={()=>setConfig({...config,customers:config.customers.filter(c=>c.customerId!==customer.customerId)})}>Remover exceção</Button></div></details>)}</div>
    <Button disabled={busy} onClick={()=>void save()}>{busy?"Salvando…":"Salvar configuração"}</Button>{message&&<p role="status" className="text-sm">{message}</p>}
  </section>;
}
